server:
  port: 8080

spring:
  application: 
    name: notemate

  # include할 파일 명시
  config:
    import: optional:application-secret.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/notemate?serverTimezone=Asia/Seoul&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #콘솔로그에 SQL 출력(log4jdbc와 비슷한 기능)
    properties:
      hibernate:
        format_sql: true #SQL 포맷팅